# Generated by Django 4.2.7 on 2025-12-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_message_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
