# Generated by Django 4.2.7 on 2025-12-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_certification_image_certification_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.TextField(blank=True, null=True),
        ),
    ]
